import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { Inter, Roboto, Poppins } from "next/font/google";
import style from "./global.css";
import styles from "./page.module.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} container`}>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
